services:
  customerservice.api:
    environment:
     - ASPNETCORE_ENVIRONMENT=Development    
     - ConnectionStrings__CustomerDbConnection=Server=mssql;Database=CustomerDb;User=sa;Password=Password1234!;MultipleActiveResultSets=true;TrustServerCertificate=true
    ports:
     - "18080:8080"  
    depends_on:
     - mssql
  
  orderservice.api:
    environment:
     - ASPNETCORE_ENVIRONMENT=Development   
     - ConnectionStrings__OrderDbConnection=Server=mssql;Database=OrderDb;User=sa;Password=Password1234!;MultipleActiveResultSets=true;TrustServerCertificate=true
     - ExternalServices__Customer__Uri=http://customerservice.api:8080   
    ports:
     - "28080:8080"  
    depends_on:
     - mssql

  mssql:
    restart: always
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Password1234!
    ports:
     - 11433:1433 

  gateway.api:
    environment:
     - ASPNETCORE_ENVIRONMENT=Development  
    ports:
     - "38080:8080"

 
    
